### ISSUE TITLE
example: ggplot_shiny(mpg) - If you select the [ plotly ] tab, an error msg appears

### ISSUE THREAD

**Issue by sfd99** [gertstulp/ggplotgui#3]
Using the GitHub example:
> ggplot_shiny(mpg)

**1)** If you select the [ ggplot ] tab, _ggplot plot is shown ok_.  
    But....
**2)** If you select the [ plotly ] tab, _error msg appears_ instead of plotly plot. 
     "Error: cannot open file '~/R/i686-pc-linux-gnu-library/3.4/plotly/R/sysdata.rdb': No such file or directory".

**Ubuntu Linux** 14.04 32-bit,   **R** version 3.4.1   and latest version **Rstudio**
plus **Plotly** PKG installed:  version 4.7.1.90...

**Comment by gertstulp** [comment]
Thank you for posting an issue! 

I don't quite know the resolution to this, but here are a few options (maybe you already tried them all):

1) Perhaps reinstall the plotly package, because the message seems somewhat similar to: https://github.com/tidyverse/readr/issues/512

2) I get the following notice when using ggplotly and ggplot2: "We recommend that you use the dev version of ggplot2 with `ggplotly()`
Install it with: `devtools::install_github('hadley/ggplot2')`". So maybe you can try this too? 

What happens if you copy the code from the "code" tab, and paste it into your R environment? Do you have the same error message then?

**Comment by GegznaV** [comment]
I had the same same error message: `cannot open file '~/R/win-library/3.4/plotly/R/sysdata.rdb': No such file or directory` 
I reinstalled `plotly` and `ggolot2` (`devtools::install_github('hadley/ggplot2')`) and and made sure, that function `plotly::ggplotly()` works fine without `ggplotgui` package. When `plotly::ggplotly()` started working, the error disappeared from the gui. 

I recommend author to close #3
